Added Brava and a few updates
marcopixel/r6operators pull request #44
Opened 2023-04-19 18:22 UTC by AidanTheJsDev

Added Brava to the list of operators, added Brava and her stats, and updated all the units for the operators.

2023-05-17 09:02 UTC, danielwerg requested changes

2023-05-17 09:02 UTC, danielwerg commented on operators/alibi/index.ts
> +  unit: "VIPERSTRIKE",
This is wrong, `unit` value should remain unmodified, instead we need to add new `squad` value

2023-05-25 17:53 UTC, danielwerg commented
Added in https://github.com/marcopixel/r6operators/commit/c4578413e73a71a1a172022e41db53003ebae618.

2023-09-05 21:17 UTC, closed without merging

2023-09-05 21:18 UTC, marcopixel commented
Sorry, missed the pull request - the changes have been done already and the icon has been added :)
Thanks for your contribution though 👍