feat: add skopos metadata and icon
marcopixel/r6operators pull request #59
Opened 2024-09-10 11:27 UTC by J4yJ4y-R6

- [x] Add Skopos icon
- [x] Add Skopos information

If you want me to change something, pls let me know.

2024-09-10 15:50 UTC, AlmostSuspense requested changes

2024-09-10 15:50 UTC, AlmostSuspense commented on operators/skopos/index.ts
> +    country: "Greek",
i believe locale codes are used instead of country names

2024-09-10 17:08 UTC, J4yJ4y-R6 commented on operators/skopos/index.ts
> +    country: "Greek",
Thanks! I forgot about that :)

2024-09-14 20:20 UTC, SwiftCODA commented
Bump @marcopixel ?

2024-09-19 07:55 UTC, marcopixel commented
@SwiftCODA @J4yJ4y-R6 

Sorry, i'm quite busy right now so i haven't had the time to check the changes yet.
I'll try to get this checked out on the weekend, so please hang in for now 🙏

2024-09-21 11:50 UTC, merged